server:
  port: 5000

spring:
  application:
    name: ilhayoung
  config:
    import: optional:file:${ENV_FILE:.env.local}[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
    mongodb:
      uri: ${MONGO_URI}

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-name: Google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - openid
              - email
              - profile
            authorization-grant-type: authorization_code
          kakao:
            provider: kakao
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  swagger-ui:
    path: /ilhayoung-api
    operations-sorter: method
    display-request-duration: true
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json

swagger:
  servers:
    local: ${SWAGGER_SERVER_LOCAL}
    prod: ${SWAGGER_SERVER_PROD}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_EXPIRED}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_EXPIRED}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG