name: CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Oracle 서버에 코드 전송 (.env.docker 제외)
      - name: Copy project files to Oracle server (excluding .env.docker)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/ilhayoung"
          rm: true
          strip_components: 1
          exclude: |
            .git/
            .github/
            build/
            .env.docker
            .env.local

      # Oracle 서버에서 .env.docker 생성 (GitHub Secrets에서 복호화)
      - name: Create .env.docker on Oracle server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/ubuntu/ilhayoung
            echo "${{ secrets.ENV_DOCKER }}" | base64 --decode > .env.docker
            echo ".env.docker created"

      # Docker Compose로 서비스 재배포
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/ubuntu/ilhayoung
            docker compose down
            docker compose --env-file .env.docker up -d --build
            echo "Deployment complete!"